set hlsearch
set incsearch
set hlsearch
set colorcolumn=80
set cursorline
set number
colorscheme evening
syntax on
syntax enable
set backspace=indent,eol,start
set history=1000
set visualbell
set tabstop=4
set expandtab
